CREATE TABLE MEMBER (
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(30 BYTE) NOT NULL,
    MEMBER_PW VARCHAR2(88 BYTE) NOT NULL,
    MEMBER_NM VARCHAR2(18 BYTE),
    MEMBER_GENDER CHAR(1 BYTE) NOT NULL CHECK(MEMBER_GENDER IN ('F', 'M')),
    MEMBER_DOB CHAR(8 BYTE) NOT NULL,
    MEMBER_EMAIL VARCHAR2(50 BYTE) NOT NULL,
    MEMBER_TEL CHAR(11 BYTE) NOT NULL,
    ENROLL_DT DATE DEFAULT SYSDATE,
    SECESSION_FL CHAR(1 BYTE) DEFAULT 'N'
);

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디(중복X)';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '회원 성별(F/M)';
COMMENT ON COLUMN MEMBER.MEMBER_DOB IS '회원 생년월일(YYYYDDMM)';
COMMENT ON COLUMN MEMBER.MEMBER_EMAIL IS '회원 이메일';
COMMENT ON COLUMN MEMBER.MEMBER_TEL IS '전화번호(- 미포함)';
COMMENT ON COLUMN MEMBER.ENROLL_DT IS '회원 가입일';
COMMENT ON COLUMN MEMBER.SECESSION_FL IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';

CREATE SEQUENCE SEQ_MEMBER_NO;

-- 샘플(pw user1234)
INSERT INTO MEMBER VALUES
    (SEQ_MEMBER_NO.NEXTVAL, 'user', 'VwO9+9Fu9H+Sndv0eF1EhuOFBJ9icjPvs1mwlK3VUpIQM/lfbolFPsgcXVAvP0d94enIlIxhRopu2dmmFb3hJg==', 
     '유저일', 'F', 19991231, 'user01@kh.or.kr',
     '01012341234', DEFAULT, DEFAULT);
     
COMMIT;

SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, 
		       MEMBER_GENDER, SUBSTR(MEMBER_DOB, 1,4)
		       || '년 ' || SUBSTR(MEMBER_DOB, 5,2) 
		       || '월 ' || SUBSTR(MEMBER_DOB, 7,2)
		       || '일' AS MEMBER_DOB, MEMBER_EMAIL,
		       MEMBER_TEL
		FROM MEMBER
		WHERE MEMBER_ID = 'user'
		AND MEMBER_PW = 'VwO9+9Fu9H+Sndv0eF1EhuOFBJ9icjPvs1mwlK3VUpIQM/lfbolFPsgcXVAvP0d94enIlIxhRopu2dmmFb3hJg=='
		AND SECESSION_FL = 'N';

UPDATE MEMBER SET MEMBER_PW = 'user1234'
WHERE MEMBER_PW = 'VwO9+9Fu9H+Sndv0eF1EhuOFBJ9icjPvs1mwlK3VUpIQM/lfbolFPsgcXVAvP0d94enIlIxhRopu2dmmFb3hJg=='
AND MEMBER_NO = 1;
