ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER semi IDENTIFIED BY semi1234;

GRANT CONNECT, RESOURCE, CREATE VIEW TO semi;

ALTER USER semi DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "BOARD" CASCADE CONSTRAINTS;
DROP TABLE "BOARDTYPE" CASCADE CONSTRAINTS;
DROP TABLE "BOARD_IMG" CASCADE CONSTRAINTS;
DROP TABLE "REPLY" CASCADE CONSTRAINTS;
DROP TABLE "BOARD_ARTICLE" CASCADE CONSTRAINTS;
DROP TABLE "HASHTAG_LIST" CASCADE CONSTRAINTS;
DROP TABLE "LIKE" CASCADE CONSTRAINTS;
DROP TABLE "ADMIN" CASCADE CONSTRAINTS;
DROP TABLE "KEYWORD" CASCADE CONSTRAINTS;
DROP TABLE "LOCATION" CASCADE CONSTRAINTS;
DROP TABLE "HASHTAG" CASCADE CONSTRAINTS;