ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER semi IDENTIFIED BY semi1234;

GRANT CONNECT, RESOURCE, CREATE VIEW TO semi;

ALTER USER semi DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;