CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(88)		NOT NULL,
	"MEMBER_NM"	VARCHAR2(18)		NOT NULL,
	"MEMBER_GENDER"	CHAR(1)		NOT NULL,
	"MEMBER_DOB"	CHAR(8)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(40)		NOT NULL,
	"MEMBER_TEL"	VARCHAR2(11)		NOT NULL,
	"PROFILE_IMG"	VARCHAR2(200)		NULL,
	"ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"SECESSION_FL"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"ADMIN_LEVEL"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호(시퀀스)';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원 아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원 이름';

COMMENT ON COLUMN "MEMBER"."MEMBER_GENDER" IS '회원 성별';

COMMENT ON COLUMN "MEMBER"."MEMBER_DOB" IS '생년월일';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '회원 전화번호';

COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '프로필 이미지';

COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '회원 가입일자';

COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부';

COMMENT ON COLUMN "MEMBER"."ADMIN_LEVEL" IS '관리자 등급';

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(150)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"UPDATE_DT"	DATE	DEFAULT SYSDATE	NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"BOARD_ST"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"BOARD_CD"	NUMBER		NOT NULL,
	"LOCATION_CODE"	NUMBER		NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호(시퀀스)';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "BOARD"."UPDATE_DT" IS '마지막수정일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."BOARD_ST" IS '게시글 상태(정상 N, 삭제 Y)';

COMMENT ON COLUMN "BOARD"."BOARD_CD" IS '게시판코드';

COMMENT ON COLUMN "BOARD"."LOCATION_CODE" IS '지역코드';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호(시퀀스)';

CREATE TABLE "BOARD_TYPE" (
	"BOARD_CD"	NUMBER		NOT NULL,
	"BOARD_NM"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_CD" IS '게시판코드';

COMMENT ON COLUMN "BOARD_TYPE"."BOARD_NM" IS '게시판이름';

CREATE TABLE "BOARD_IMG" (
	"IMG_NO"	NUMBER		NOT NULL,
	"IMG_SIZE"	NUMBER		NOT NULL,
	"IMG_RENAME"	VARCHAR2(500)		NOT NULL,
	"IMG_ORIGINAL"	VARCHAR2(500)		NOT NULL,
	"IMG_LEVEL"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_IMG"."IMG_NO" IS '이미지번호(시퀀스)';

COMMENT ON COLUMN "BOARD_IMG"."IMG_SIZE" IS '전체(1)/반(0) 크기';

COMMENT ON COLUMN "BOARD_IMG"."IMG_RENAME" IS '이미지저장경로+변경명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_ORIGINAL" IS '이미지원본명';

COMMENT ON COLUMN "BOARD_IMG"."IMG_LEVEL" IS '이미지위치지정번호';

COMMENT ON COLUMN "BOARD_IMG"."BOARD_NO" IS '게시글 번호(시퀀스)';

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REPLY_ST"	CHAR(1)	DEFAULT 'N'	NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "REPLY"."REPLY_NO" IS '댓글번호(시퀀스)';

COMMENT ON COLUMN "REPLY"."REPLY_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "REPLY"."REPLY_ST" IS '댓글 상태(정상 N, 삭제 Y)';

COMMENT ON COLUMN "REPLY"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "REPLY"."BOARD_NO" IS '게시글 번호(시퀀스)';

COMMENT ON COLUMN "REPLY"."MEMBER_NO" IS '회원번호(시퀀스)';

CREATE TABLE "BOARD_ARTICLE" (
	"BOARD_CT_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(4000)		NOT NULL,
	"CONTENT_SIZE"	NUMBER		NOT NULL,
	"CONTENT_LEVEL"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "BOARD_ARTICLE"."BOARD_CT_NO" IS '게시글 내용 번호(시퀀스)';

COMMENT ON COLUMN "BOARD_ARTICLE"."CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD_ARTICLE"."CONTENT_SIZE" IS '전체(1)/반(0) 크기';

COMMENT ON COLUMN "BOARD_ARTICLE"."CONTENT_LEVEL" IS '게시글 내 순서';

COMMENT ON COLUMN "BOARD_ARTICLE"."BOARD_NO" IS '게시글 번호(시퀀스)';

CREATE TABLE "HASHTAG_LIST" (
	"HASHTAG_NO"	NUMBER		NOT NULL,
	"HASHTAG_NM"	VARCHAR2(40)		NOT NULL,
	"HASHTAG_CAT"	CHAR(20)		NOT NULL
);

COMMENT ON COLUMN "HASHTAG_LIST"."HASHTAG_NO" IS '태그번호(시퀀스)';

COMMENT ON COLUMN "HASHTAG_LIST"."HASHTAG_NM" IS '태그이름';

COMMENT ON COLUMN "HASHTAG_LIST"."HASHTAG_CAT" IS '태그 카테고리';

CREATE TABLE "LIKE" (
	"BOARD_REPLY_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "LIKE"."BOARD_REPLY_NO" IS '게시글, 댓글번호';

COMMENT ON COLUMN "LIKE"."MEMBER_NO" IS '회원번호(시퀀스)';

CREATE TABLE "ADMIN" (
	"ADMIN_LEVEL"	NUMBER		NOT NULL,
	"ADMIN_AUTHORITY"	CHAR(3)	DEFAULT '000'	NOT NULL
);

COMMENT ON COLUMN "ADMIN"."ADMIN_LEVEL" IS '관리자 등급';

COMMENT ON COLUMN "ADMIN"."ADMIN_AUTHORITY" IS '관리자 권한';

CREATE TABLE "KEYWORD" (
	"KEYWORD"	VARCHAR2(100)		NOT NULL,
	"SEARCH_CNT"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "KEYWORD"."KEYWORD" IS '검색어 내용';

COMMENT ON COLUMN "KEYWORD"."SEARCH_CNT" IS '검색 횟수';

CREATE TABLE "LOCATION" (
	"LOCATION_CODE"	NUMBER		NOT NULL,
	"LOCATION_NM"	VARCHAR2(100)		NOT NULL
);

COMMENT ON COLUMN "LOCATION"."LOCATION_CODE" IS '지역코드';

COMMENT ON COLUMN "LOCATION"."LOCATION_NM" IS '지역명';

CREATE TABLE "HASHTAG" (
    "HASHTAG_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL
);

COMMENT ON COLUMN "HASHTAG"."HASHTAG_NO" IS '태그번호(시퀀스)';

COMMENT ON COLUMN "HASHTAG"."BOARD_NO" IS '게시글 번호(시퀀스)';

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_TYPE" ADD CONSTRAINT "PK_BOARD_TYPE" PRIMARY KEY (
	"BOARD_CD"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "PK_BOARD_IMG" PRIMARY KEY (
	"IMG_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "PK_REPLY" PRIMARY KEY (
	"REPLY_NO"
);

ALTER TABLE "BOARD_ARTICLE" ADD CONSTRAINT "PK_BOARD_ARTICLE" PRIMARY KEY (
	"BOARD_CT_NO"
);

ALTER TABLE "HASHTAG_LIST" ADD CONSTRAINT "PK_HASHTAG_LIST" PRIMARY KEY (
	"HASHTAG_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "PK_LIKE" PRIMARY KEY (
	"BOARD_REPLY_NO",
	"MEMBER_NO"
);

ALTER TABLE "ADMIN" ADD CONSTRAINT "PK_ADMIN" PRIMARY KEY (
	"ADMIN_LEVEL"
);

ALTER TABLE "LOCATION" ADD CONSTRAINT "PK_LOCATION" PRIMARY KEY (
	"LOCATION_CODE"
);

ALTER TABLE "HASHTAG" ADD CONSTRAINT "PK_HASHTAG" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_ADMIN_TO_MEMBER_1" FOREIGN KEY (
	"ADMIN_LEVEL"
)
REFERENCES "ADMIN" (
	"ADMIN_LEVEL"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBER_TO_BOARD_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_TYPE_TO_BOARD_1" FOREIGN KEY (
	"BOARD_CD"
)
REFERENCES "BOARD_TYPE" (
	"BOARD_CD"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_LOCATION_TO_BOARD_1" FOREIGN KEY (
	"LOCATION_CODE"
)
REFERENCES "LOCATION" (
	"LOCATION_CODE"
);

ALTER TABLE "BOARD_IMG" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_BOARD_TO_REPLY_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REPLY" ADD CONSTRAINT "FK_MEMBER_TO_REPLY_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "BOARD_ARTICLE" ADD CONSTRAINT "FK_BOARD_TO_BOARD_ARTICLE_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"MEMBER_NO"
)
REFERENCES "MEMBER" (
	"MEMBER_NO"
);

ALTER TABLE "HASHTAG" ADD CONSTRAINT "FK_BOARD_TO_HASHTAG_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "BOARD" (
	"BOARD_NO"
);

ALTER TABLE "HASHTAG" ADD CONSTRAINT "FK_HASHTAG_LIST_TO_HASHTAG_1" FOREIGN KEY (
	"HASHTAG_NO"
)
REFERENCES "HASHTAG_LIST" (
	"HASHTAG_NO"
);
