 CREATE TABLE "LOCATION" 
   (	"LOCATION_CODE" NUMBER, 
	"LOCATION_NM" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
REM INSERTING into LOCATION
SET DEFINE OFF;
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51730,'강원특별자치도 횡성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51790,'강원특별자치도 화천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46790,'전남 화순군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41594,'경기 화성시동탄출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41590,'경기 화성시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51720,'강원특별자치도 홍천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44800,'충남 홍성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26350,'부산 해운대구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46820,'전남 해남군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48890,'경남 합천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46860,'전남 함평군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48870,'경남 함양군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48730,'경남 함안군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48850,'경남 하동군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41450,'경기 하남시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41362,'경기 풍양출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47110,'경북 포항시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41650,'경기 포천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41220,'경기 평택시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51760,'강원특별자치도 평창군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41480,'경기 파주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48220,'경남 통영시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44825,'충남 태안군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51190,'강원특별자치도 태백시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47850,'경북 칠곡군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43130,'충북 충주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51110,'강원특별자치도 춘천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43110,'충북 청주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44790,'충남 청양군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47750,'경북 청송군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47820,'경북 청도군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51780,'강원특별자치도 철원군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44130,'충남 천안시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48120,'경남 창원시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48740,'경남 창녕군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43750,'충북 진천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48170,'경남 진주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52720,'전북특별자치도 진안군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46900,'전남 진도군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43745,'충북 증평군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11260,'서울 중랑구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28118,'인천 중구용유출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28114,'인천 중구영종출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (31110,'울산 중구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26110,'부산 중구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27110,'대구 중구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28110,'인천 중구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (30140,'대전 중구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11140,'서울 중구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11110,'서울 종로구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43150,'충북 제천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (50110,'제주특별자치도 제주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52180,'전북특별자치도 정읍시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51770,'강원특별자치도 정선군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52110,'전북특별자치도 전주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46800,'전남 장흥군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48252,'경남 장유출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52740,'전북특별자치도 장수군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46880,'전남 장성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52750,'전북특별자치도 임실군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51810,'강원특별자치도 인제군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52140,'전북특별자치도 익산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41500,'경기 이천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41150,'경기 의정부시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41430,'경기 의왕시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47730,'경북 의성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48720,'경남 의령군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43770,'충북 음성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11380,'서울 은평구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (30200,'대전 유성구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51130,'강원특별자치도 원주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47930,'경북 울진군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (31710,'울산 울주군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47940,'경북 울릉군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41460,'경기 용인시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11170,'서울 용산구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52710,'전북특별자치도 완주군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46890,'전남 완도군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28720,'인천 옹진군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43730,'충북 옥천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41370,'경기 오산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47900,'경북 예천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44810,'충남 예산군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47230,'경북 영천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47210,'경북 영주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51750,'강원특별자치도 영월군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47760,'경북 영양군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46830,'전남 영암군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11560,'서울 영등포구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43740,'충북 영동군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26200,'부산 영도구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47770,'경북 영덕군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46870,'전남 영광군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41800,'경기 연천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26470,'부산 연제구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28185,'인천 연수구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41670,'경기 여주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46130,'전남 여수시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41830,'경기 양평군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11470,'서울 양천구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41630,'경기 양주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51830,'강원특별자치도 양양군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48332,'경남 양산시웅상출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48330,'경남 양산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51800,'강원특별자치도 양구군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41224,'경기 안중출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41170,'경기 안양시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41550,'경기 안성시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41270,'경기 안산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47170,'경북 안동시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44200,'충남 아산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46910,'전남 신안군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41390,'경기 시흥시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46150,'전남 순천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52770,'전북특별자치도 순창군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41110,'경기 수원시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26500,'부산 수영구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27260,'대구 수성구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11710,'서울 송파구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41222,'경기 송탄출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51210,'강원특별자치도 속초시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47840,'경북 성주군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11290,'서울 성북구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11200,'서울 성동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41130,'경기 성남시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11650,'서울 서초구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44770,'충남 서천군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44210,'충남 서산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11410,'서울 서대문구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (50130,'제주특별자치도 서귀포시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28265,'인천 서구검단출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26140,'부산 서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27170,'대구 서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28260,'인천 서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (29140,'광주 서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (30170,'대전 서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47250,'경북 상주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51230,'강원특별자치도 삼척시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48860,'경남 산청군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26380,'부산 사하구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48240,'경남 사천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48245,'경남 사천남양출장소');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26530,'부산 사상구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (31200,'울산 북구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26320,'부산 북구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27230,'대구 북구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (29170,'광주 북구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28237,'인천 부평구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41190,'경기 부천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44760,'충남 부여군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52800,'전북특별자치도 부안군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26230,'부산 부산진구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47920,'경북 봉화군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43720,'충북 보은군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46780,'전남 보성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44180,'충남 보령시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48270,'경남 밀양시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28177,'인천 미추홀구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47280,'경북 문경시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52730,'전북특별자치도 무주군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46840,'전남 무안군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46110,'전남 목포시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11440,'서울 마포구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51170,'강원특별자치도 동해시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11590,'서울 동작구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26260,'부산 동래구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41250,'경기 동두천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11230,'서울 동대문구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (31170,'울산 동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26170,'부산 동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27140,'대구 동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28140,'인천 동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (29110,'광주 동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (30110,'대전 동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11320,'서울 도봉구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (30230,'대전 대덕구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44270,'충남 당진시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46710,'전남 담양군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27710,'대구 달성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27290,'대구 달서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43800,'충북 단양군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44230,'충남 논산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11350,'서울 노원구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48840,'경남 남해군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52190,'전북특별자치도 남원시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41360,'경기 남양주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28200,'인천 남동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (31140,'울산 남구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (29155,'광주 남구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26290,'부산 남구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27200,'대구 남구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46170,'전남 나주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48250,'경남 김해시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41570,'경기 김포시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47150,'경북 김천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52210,'전북특별자치도 김제시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26710,'부산 기장군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11545,'서울 금천구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26410,'부산 금정구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44710,'충남 금산군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41410,'경기 군포시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (27720,'대구 군위군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52130,'전북특별자치도 군산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47190,'경북 구미시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41310,'경기 구리시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11530,'서울 구로구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46730,'전남 구례군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (43760,'충북 괴산군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11215,'서울 광진구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41610,'경기 광주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46230,'전남 광양시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (29200,'광주 광산구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41210,'경기 광명시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11620,'서울 관악구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41290,'경기 과천시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44150,'충남 공주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46720,'전남 곡성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46770,'전남 고흥군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (52790,'전북특별자치도 고창군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41280,'경기 고양시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51820,'강원특별자치도 고성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48820,'경남 고성군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47830,'경북 고령군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28245,'인천 계양구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (44250,'충남 계룡시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47130,'경북 경주시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (47290,'경북 경산시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48880,'경남 거창군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (48310,'경남 거제시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (28710,'인천 강화군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (46810,'전남 강진군');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (26440,'부산 강서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11500,'서울 강서구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11305,'서울 강북구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (51150,'강원특별자치도 강릉시');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11740,'서울 강동구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (11680,'서울 강남구');
Insert into LOCATION (LOCATION_CODE,LOCATION_NM) values (41820,'경기 가평군');
COMMIT;

CREATE SEQUENCE SEQ_IMG_NO NOCACHE;
COMMIT;
SELECT * FROM BOARd_ARTICLE;
CREATE SEQUENCE SEQ_ARTICLE_NO NOCACHE;

CREATE SEQUENCE SEQ_HASHTAG_NO NOCACHE;


CREATE SEQUENCE SEQ_BOARD_CT_NO NOCACHE;

SEQ_HASHTAG_NO
SELECT * FROM BOARD;